# Generated by Django 3.2.5 on 2022-01-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('githubuser', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Github Username')),
                ('image_link', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Image Link')),
                ('user_name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='User Name')),
            ],
        ),
    ]
